apps/movies/urls.py
from django.urls import path

from . import views


app_name = 'movies'


# Standard views
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('actor/', views.ActorView.as_view(), name='actor'),
    path('movie/', views.MovieView.as_view(), name='movie'),
]

# Ajax views
urlpatterns += [
    path('api/movies/locations/',
         views.api_get_locations,
         name='api_get_locations'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('apps.movies.urls', namespace='movies')),
]

apps/movies/models.py
from django.db import models

# Create your models here.

apps/movies/views.py
from django.views import generic
from django import http

from .api import MovieApi
from .api import ImdbActorApi
from .api import ImdbMovieApi


class IndexView(generic.TemplateView):
    '''Index page'''
    template_name = 'movies/index.html'
    actors = None
    movies = None

    def get(self, request, *args, **kwargs):
        self.api = MovieApi().fetch(request)
        return super().get(self.api.request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs['actors'] = self.api.get_actor_list()
        kwargs['movies'] = self.api.get_movie_list()
        kwargs['locations'] = self.api.get_location_list()
        kwargs['random_fact'] = self.api.get_random_fun_fact()
        return kwargs


class ActorView(generic.TemplateView):
    '''Actor page'''
    template_name = 'movies/actor.html'
    actor = None
    keyword_name = 'name'

    def get(self, request, *args, **kwargs):
        self.actor = request.GET.get('name')
        if self.actor:
            # Get location information based on actor
            api = MovieApi().fetch(request)
            api.filter(actor=self.actor)
            self.objects = api.get_objects()
            if not self.objects:
                raise http.Http404('Data not available for this actor')
            # Get profile picure of actor from IMDB API
            imdb_api = ImdbActorApi(self.actor)
            imdb_api = imdb_api.fetch(request)
            self.imdb = imdb_api.get_objects() or None
        else:
            return http.HttpResponse('Bad request', status=400)
        return super().get(api.request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs['locations'] = self.objects
        kwargs['actor'] = self.actor.title()
        if self.imdb:
            kwargs['imdb'] = self.imdb[0]
        return kwargs


class MovieView(generic.TemplateView):
    '''Movie page'''
    template_name = 'movies/movie.html'
    title = None

    def get(self, request, *args, **kwargs):
        self.title = request.GET.get('title')
        if self.title:
            api = MovieApi().fetch(self.request)
            api.filter(title=self.title)
            self.objects = api.get_objects()
            if self.objects:
                self.imdb = ImdbMovieApi(self.title)
                self.imdb = self.imdb.filter(
                    year=self.objects[0]['release_year']
                )
                self.imdb = self.imdb.fetch(request)
                self.imdb = self.imdb.get_objects() or None
            else:
                raise http.Http404('Data not available for this title')
        else:
            return http.HttpResponse('Bad request', status=400)
        return super().get(api.request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        '''Arrange data

        Filter data by location, and then by actor,
        To make sure we have no empty data or duplicates.
        '''
        # Movie locations
        kwargs = super().get_context_data(**kwargs)
        locations = set()
        for obj in self.objects:
            location = obj.get('locations')
            if location:
                locations.add(location)
        kwargs['locations'] = sorted(list(locations))
        kwargs['movie'] = self.objects[0]
        # Movie actors
        actors = set()
        for obj in self.objects:
            for key in obj.keys():
                if key in MovieApi().actor_fields:
                    actor = obj.get(key, None)
                    if actor:
                        actors.add(obj.get(key))
        kwargs['actors'] = sorted(list(actors))
        if self.imdb:
            kwargs['imdb'] = self.imdb
        return kwargs


def api_get_locations(request):
    '''Returns a locations list in JSON format'''
    if not request.is_ajax():
        raise http.HttpResponse("Forbidden. This view is an AJAX view", 403)
    api = MovieApi().fetch(request)
    locations = api.get_location_list()
    return http.JsonResponse({ 'locations': locations })

apps/movies/templates/movies/actor.html
{% extends 'base.html' %}

{% block content %}

{% if locations %}
    <div class="row mt-5">
        <div class="col-sm-8 mx-auto black-bg">
            <h1 class="mt-4 mb-0 text-center">{{ actor }}</h1>
            <p class="text-center mt-0">Actor</p>

            {% if imdb %}
                <div class="row mx-auto my-3">
                    {% if imdb.image.thumb %}
                        <div class="col-md-3 text-center">
                            <img src="{{ imdb.image.thumb }}" class="img-fluid actor-thumbnail mb-3">
                        </div>
                    {% endif %}

                    <div class="col-md-9">
                        <p>{{ imdb.description }} <a href="http://www.imdb.com/name/{{ imdb.person_id }}/bio" target="_blank">See more at IMDB <i class="fas fa-chevron-right"></i></a></p>
                    </div>
                </div>
            {% endif %}

            <p>The actor had filmed in {% if locations|length > 1 %}these{% else %}this{% endif %} location{{ locations|pluralize:'s' }} in San Francisco:</p>

            <table class="table" width="100%">
                <tbody>
                    {% for location in locations %}
                        <tr>
                            <td>
                                <a href="javascript:void(0)" 
                                   class="location-link"
                                   data-location="{{ location.locations }}"
                                   data-target="#mapModal"
                                   data-toggle="modal">{{ location.locations }}</a>
                            </td>

                            <td align="right"><a href="{% url 'movies:movie' %}?title={{ location.title|urlencode }}">{{ location.title }} ({{ location.release_year }})</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
               
        </div>
    </div>
{% else %}
    <p>The actor had no record of any specific filming location in SF.</p>
{% endif %}

{% include 'includes/map_modal.html' %}
{% endblock %}

apps/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<!-- <div class="row my-3">
    <div class="col-sm-6 mx-auto">
        <form class="search-form">
            <input type="text" name="" class="form-control search-form-input" placeholder="Search here" autofocus>
        </form>
    </div>
</div> -->

<!-- <div class="row">
    <div class="col-xs-12">
        <div id="map" style="width: 500px; height: 500px"></div>
    </div>
</div> -->

<div class="row">
    <div class="col-sm-6 mx-auto my-5 py-4 black-bg">
            <!-- <h2 class="text-center">Location Fun Fact!</h2> -->

            <h3 class="text-center fun-fact-title"><a href="{% url 'movies:movie' %}?title={{ random_fact.title|urlencode }}">{{ random_fact.title }}</a></h3>

            <p class="text-center lead"><a class="text-center fun-fact-location location-link" data-location="{{ random_fact.locations }}" data-toggle="modal" data-target="#mapModal"><i class="fas fa-map-marker-alt"></i>&nbsp;&nbsp;{{ random_fact.locations }}</a></p>

            <p class="text-center fun-fact-fact">{{ random_fact.fun_facts }}</p>
    </div>
</div>

{% include 'includes/map_modal.html' %}

{% endblock %}

{% block inline_script %}
<script type="text/javascript" src="{% static 'js/views/movies_index.js' %}"></script>
{% endblock %}

apps/movies/templates/movies/movie.html
{% extends 'base.html' %}
{% load movies %}

{% block content %}
    
<div class="row mt-5">
    <div class="col-sm-8 mx-auto black-bg mb-5">
        <h1 class="mt-4 mb-0 text-center">{{ movie.title }}</h1>
        <p class="text-center mt-0">Movie | {{ movie.release_year }}</p>

        {% if imdb.Response != 'False' %}
            <div class="row mx-auto my-3">
                <div class="col-md-3 text-center">
                    {% if imdb.Poster != 'N/A' %}
                        <img src="{{ imdb.Poster }}" class="img-fluid actor-thumbnail mb-3">
                    {% endif %}
                </div>

                {% if imdb.Poster == 'N/A' %}
                    <div class="col-xs-12">
                {% else %}
                    <div class="col-md-9">
                {% endif %}

                    <p>{{ imdb.Plot|truncatewords:120 }} <a href="https://www.imdb.com/title/{{ imdb.imdbID }}/" target="_blank">See more at IMDB <i class="fas fa-chevron-right"></i></a></p>

                    {% if imdb.imdbRating != 'N/A' %}
                        <p>Rating: <span class="imdb-rating {{ imdb.imdbRating|imdb_rating_color }}">{{ imdb.imdbRating }}</span></p>
                    {% endif %}

                    {% if imdb.Actors %}
                        <!-- <p><span class="sub-title">Actors</span><br />{{ imdb.Actors }}</p> -->
                    {% endif %}
                </div>
            </div>
        {% endif %}

        <div class="row mx-auto">
            <div class="col-md-6 mt-3">
                <h2>Actors:</h2>

                <ul>
                    {% for actor in actors %}
                        <li>{{ actor }}</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="col-md-6 mt-3">
                <h2>Filming locations:</h2>

                <ul>
                    {% for location in locations %}
                        <li><a href="javascript:void(0)" 
                               class="location-link"
                               data-location="{{ location }}"
                               data-target="#mapModal"
                               data-toggle="modal">{{ location }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% include 'includes/map_modal.html' %}
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}Movie San Francisco</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <script src="https://maps.google.com/maps/api/js?key=AIzaSyDK1ocDKw90uMRMZCSY4FgcGX6iBZE53OY" 
            type="text/javascript"></script>
    {% block head_script %}{% endblock %}
</head>

<body>
<div class="container-fluid">
    <header>
        <h1 class="branding"><a href="{% url 'movies:index' %}">Movie San Francisco</a></h1>
        <p class="slogan">Your guide to SF movie locations</p>
    </header>
</div>

<div class="container-fluid">
{% block content %}{% endblock %}
</div>

<!-- inline scripts -->
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/fontawesome-all.min.js' %}"></script>
<script src="{% static 'js/google-map.js' %}"></script>
{% block inline_script %}{% endblock %}
<!-- end of inline scripts -->
</body>

</html>

templates/includes/map_modal.html
<!-- Map modal -->
<div class="modal fade map-modal" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="mapModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mapModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="map-wrapper">
            <div id="map"></div>
            &nbsp;
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end of Map modal -->